"""
Cross-implementation vectors for transcript-bound security protocol negotiation.

Two implementations can agree on the design and still fail to interoperate over
a single byte: a different canonical encoding, a different signature prefix, or
different protobuf field numbers. Each side's own tests pass and the handshake
still fails in the field. ``tests/fixtures/transcript-binding-vectors.json``
pins the shared wire format so that class of mismatch fails here instead.

The fixture is generated by the TypeScript implementation
(``scripts/generate-transcript-vectors.js`` in js-libp2p-noise) from fixed
inputs, so no handshake is needed to check agreement. If a wire-format change
is deliberate, regenerate the fixture on both sides in the same change and say
so. A silent regeneration defeats the purpose of the file.

See ``TRANSCRIPT_BINDING_SPEC.md`` for the design.
"""

import json
from pathlib import Path

import pytest

from libp2p.crypto.ed25519 import (
    create_new_key_pair,
)
from libp2p.crypto.x25519 import (
    X25519PublicKey,
)
from libp2p.security.noise.messages import (
    NoiseHandshakePayload,
    make_data_to_be_signed,
)
from libp2p.security.noise.pb import noise_pb2
from libp2p.security.noise.transcript_binding import (
    IdentityBinding,
    canonical_protocols,
    transcript_signature_payload,
    verify_transcript_binding,
)

_REPO_ROOT = Path(__file__).resolve().parents[3]
_FIXTURE = _REPO_ROOT / "tests" / "fixtures" / "transcript-binding-vectors.json"


def _load() -> dict:
    if not _FIXTURE.exists():  # pragma: no cover - fixture is committed
        pytest.skip(f"fixture not found: {_FIXTURE}")
    with _FIXTURE.open(encoding="utf-8") as handle:
        return json.load(handle)


_DATA = _load()
_VECTORS = _DATA["vectors"]


def _key_pair():
    return create_new_key_pair(bytes.fromhex(_DATA["identity_key_seed"]))


def _static_pubkey() -> X25519PublicKey:
    return X25519PublicKey.from_bytes(bytes.fromhex(_DATA["noise_static_public_key"]))


def _payload_hash() -> bytes:
    return bytes.fromhex(_DATA["payload_hash"])


def test_fixture_is_not_empty() -> None:
    assert len(_VECTORS) >= 5


def test_seeded_identity_key_agrees_across_implementations() -> None:
    """
    Both sides must derive the same identity key from the same seed.

    If this fails nothing else in the file means anything, because the two
    implementations are not talking about the same key.
    """
    assert _key_pair().public_key.to_bytes().hex() == _DATA["identity_public_key"]


def test_protobuf_field_numbers_match() -> None:
    """
    Field numbers are wire format. A mismatch here is silent data loss: the
    peer parses the field as unknown and skips it, so the check simply never
    fires rather than failing loudly.
    """
    expected = _DATA["protobuf_field_numbers"]
    fields = {f.name: f.number for f in noise_pb2.NoiseExtensions.DESCRIPTOR.fields}

    assert (
        fields["security_protocols"] == expected["NoiseExtensions.security_protocols"]
    )
    assert fields["transcript_sig"] == expected["NoiseExtensions.transcript_sig"]


def test_signature_prefixes_match() -> None:
    from libp2p.security.noise.messages import SIGNED_DATA_PREFIX
    from libp2p.security.noise.transcript_binding import TRANSCRIPT_SIG_PREFIX

    assert TRANSCRIPT_SIG_PREFIX.decode("utf-8") == _DATA["transcript_sig_prefix"]
    assert SIGNED_DATA_PREFIX == _DATA["identity_sig_prefix"]


@pytest.mark.parametrize(
    "vector", _VECTORS, ids=[",".join(v["protocols"]) for v in _VECTORS]
)
def test_canonical_encoding_matches(vector: dict) -> None:
    assert (
        canonical_protocols(vector["protocols"]).hex() == vector["canonical_protocols"]
    )


@pytest.mark.parametrize(
    "vector", _VECTORS, ids=[",".join(v["protocols"]) for v in _VECTORS]
)
def test_transcript_signature_payload_matches(vector: dict) -> None:
    payload = transcript_signature_payload(_payload_hash(), vector["protocols"])

    assert payload.hex() == vector["transcript_sig_payload"]


@pytest.mark.parametrize(
    "vector", _VECTORS, ids=[",".join(v["protocols"]) for v in _VECTORS]
)
def test_bound_identity_signature_payload_matches(vector: dict) -> None:
    binding = IdentityBinding(
        payload_hash=_payload_hash(), protocols=tuple(vector["protocols"])
    )
    data = make_data_to_be_signed(_static_pubkey(), binding)

    assert data.hex() == vector["identity_sig_payload_bound"]


@pytest.mark.parametrize(
    "vector", _VECTORS, ids=[",".join(v["protocols"]) for v in _VECTORS]
)
def test_verifies_a_transcript_signature_produced_by_the_other_implementation(
    vector: dict,
) -> None:
    """
    The signature in the fixture was produced by the TypeScript code. Verifying
    it here proves both sides sign the same bytes, which a same-implementation
    round trip cannot show.
    """
    assert verify_transcript_binding(
        _key_pair().public_key,
        _payload_hash(),
        vector["protocols"],
        bytes.fromhex(vector["extension_variant"]["transcript_sig"]),
    )


@pytest.mark.parametrize(
    "vector", _VECTORS, ids=[",".join(v["protocols"]) for v in _VECTORS]
)
def test_parses_a_handshake_payload_produced_by_the_other_implementation(
    vector: dict,
) -> None:
    raw = bytes.fromhex(vector["extension_variant"]["handshake_payload"])
    payload = NoiseHandshakePayload.deserialize(raw)

    assert payload.extensions is not None
    assert list(payload.extensions.security_protocols) == vector["protocols"]
    assert (
        payload.extensions.transcript_sig.hex()
        == vector["extension_variant"]["transcript_sig"]
    )


@pytest.mark.parametrize(
    "vector", _VECTORS, ids=[",".join(v["protocols"]) for v in _VECTORS]
)
def test_rejects_a_transcript_signature_bound_to_another_transcript(
    vector: dict,
) -> None:
    """A signature from the fixture must not verify under a different hash."""
    other_hash = bytes(32)

    assert not verify_transcript_binding(
        _key_pair().public_key,
        other_hash,
        vector["protocols"],
        bytes.fromhex(vector["extension_variant"]["transcript_sig"]),
    )


def test_length_prefixes_separate_lists_that_would_otherwise_collide() -> None:
    """
    ``['ab', 'c']`` and ``['a', 'bc']`` are both in the fixture precisely
    because naive concatenation maps them to the same bytes. An implementation
    that drops the length prefixes passes its own round-trip tests and fails
    here.
    """
    by_protocols = {tuple(v["protocols"]): v for v in _VECTORS}
    first = by_protocols[("ab", "c")]
    second = by_protocols[("a", "bc")]

    assert first["canonical_protocols"] != second["canonical_protocols"]
    assert (
        canonical_protocols(["ab", "c"]).hex() != canonical_protocols(["a", "bc"]).hex()
    )


def test_protocol_identifiers_match() -> None:
    """
    The identity variant moves the protocol identifier, so both constants are
    duplicated in every implementation.

    A typo in one of them fails no implementation's own tests: it surfaces in
    the field as two peers with no protocol in common. Checking them against
    the shared fixture makes that a test failure instead.
    """
    from libp2p.security.noise.pq.transport_pq import (
        IDENTITY_BOUND_PROTOCOL_ID,
        PROTOCOL_ID,
    )

    recorded = _DATA["protocol_ids"]

    assert str(PROTOCOL_ID) == recorded["hybrid"]
    assert str(IDENTITY_BOUND_PROTOCOL_ID) == recorded["hybrid_identity_bound"]
    assert recorded["hybrid"] != recorded["hybrid_identity_bound"]
