[tox]
envlist = py311, lint
isolated_build = true

[testenv]
commands_pre =
    python -m pip install --upgrade pip
    python -m pip install -e .[test]
commands =
    pytest {posargs:tests}

[testenv:lint]
commands_pre =
    python -m pip install --upgrade pip
    python -m pip install -e .[dev]
commands =
    ruff check .
    ruff format --check .
    mypy py_ipfs_lite

