[tox]
envlist = py310, py311, py312, py313, lint
isolated_build = true

[testenv]
deps =
    pytest
    pytest-cov
    pytest-trio
    -e .[test]
commands = pytest {posargs:tests}

[testenv:lint]
deps = pre-commit
commands = pre-commit run --all-files --show-diff-on-failure
