"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _Status:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _StatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Status.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    OK: _Status.ValueType  # 0
    RESERVATION_REFUSED: _Status.ValueType  # 100
    RESOURCE_LIMIT_EXCEEDED: _Status.ValueType  # 101
    PERMISSION_DENIED: _Status.ValueType  # 102
    CONNECTION_FAILED: _Status.ValueType  # 200
    DIAL_REFUSED: _Status.ValueType  # 201
    STOP_FAILED: _Status.ValueType  # 300
    MALFORMED_MESSAGE: _Status.ValueType  # 400
    INTERNAL_ERROR: _Status.ValueType  # 500

class Status(_Status, metaclass=_StatusEnumTypeWrapper):
    """Status codes for relay operations"""

OK: Status.ValueType  # 0
RESERVATION_REFUSED: Status.ValueType  # 100
RESOURCE_LIMIT_EXCEEDED: Status.ValueType  # 101
PERMISSION_DENIED: Status.ValueType  # 102
CONNECTION_FAILED: Status.ValueType  # 200
DIAL_REFUSED: Status.ValueType  # 201
STOP_FAILED: Status.ValueType  # 300
MALFORMED_MESSAGE: Status.ValueType  # 400
INTERNAL_ERROR: Status.ValueType  # 500
global___Status = Status

# HopMessage Type enum classes
class _HopMessageType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _HopMessageTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_HopMessageType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    RESERVE: _HopMessageType.ValueType  # 0
    CONNECT: _HopMessageType.ValueType  # 1
    STATUS: _HopMessageType.ValueType  # 2

class HopMessageType(_HopMessageType, metaclass=_HopMessageTypeEnumTypeWrapper):
    """Message types for HopMessage"""
    pass

# StopMessage Type enum classes
class _StopMessageType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _StopMessageTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_StopMessageType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    CONNECT: _StopMessageType.ValueType  # 0
    STATUS: _StopMessageType.ValueType  # 1

class StopMessageType(_StopMessageType, metaclass=_StopMessageTypeEnumTypeWrapper):
    """Message types for StopMessage"""
    pass

@typing.final
class HopMessage(google.protobuf.message.Message):
    """HopMessage is used to open relay connections."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    # Use class references that are defined above
    Type = HopMessageType
    RESERVE: builtins.int  # 0
    CONNECT: builtins.int  # 1
    STATUS: builtins.int  # 2

    TYPE_FIELD_NUMBER: builtins.int
    PEER_FIELD_NUMBER: builtins.int
    RESERVATION_FIELD_NUMBER: builtins.int
    LIMIT_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    type: builtins.int
    peer: builtins.bytes
    @property
    def reservation(self) -> global___Reservation: ...
    @property
    def limit(self) -> global___Limit: ...
    @property
    def status(self) -> global___Status: ...
    def __init__(
        self,
        *,
        type: builtins.int = ...,
        peer: builtins.bytes = ...,
        reservation: global___Reservation | None = ...,
        limit: global___Limit | None = ...,
        status: global___Status | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["limit", b"limit", "peer", b"peer", "reservation", b"reservation", "status", b"status"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["limit", b"limit", "peer", b"peer", "reservation", b"reservation", "status", b"status", "type", b"type"]) -> None: ...

global___HopMessage = HopMessage

@typing.final
class StopMessage(google.protobuf.message.Message):
    """StopMessage is used to stop relay connections."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    # Use class references that are defined above
    Type = StopMessageType
    CONNECT: builtins.int  # 0
    STATUS: builtins.int  # 1

    TYPE_FIELD_NUMBER: builtins.int
    PEER_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    type: builtins.int
    peer: builtins.bytes
    @property
    def status(self) -> global___Status: ...
    def __init__(
        self,
        *,
        type: builtins.int = ...,
        peer: builtins.bytes = ...,
        status: global___Status | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["peer", b"peer", "status", b"status"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["peer", b"peer", "status", b"status", "type", b"type"]) -> None: ...

global___StopMessage = StopMessage

@typing.final
class Reservation(google.protobuf.message.Message):
    """Reservation details for relay connections."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VOUCHER_FIELD_NUMBER: builtins.int
    SIGNATURE_FIELD_NUMBER: builtins.int
    EXPIRE_FIELD_NUMBER: builtins.int
    ADDRS_FIELD_NUMBER: builtins.int
    voucher: builtins.bytes
    signature: builtins.bytes
    expire: builtins.int
    @property
    def addrs(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bytes]: ...
    def __init__(
        self,
        *,
        voucher: builtins.bytes = ...,
        signature: builtins.bytes = ...,
        expire: builtins.int = ...,
        addrs: collections.abc.Iterable[builtins.bytes] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["addrs", b"addrs", "expire", b"expire", "signature", b"signature", "voucher", b"voucher"]) -> None: ...

global___Reservation = Reservation

@typing.final
class Limit(google.protobuf.message.Message):
    """Resource limits for relay connections."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DURATION_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    duration: builtins.int
    data: builtins.int
    def __init__(
        self,
        *,
        duration: builtins.int = ...,
        data: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["data", b"data", "duration", b"duration"]) -> None: ...

global___Limit = Limit 