"""
Cross-implementation test vectors for
``Noise_XXhfs_25519+MLKEM768_ChaChaPoly_SHA256`` (``/noise-mlkem768-hfs/0.2.0``).

Replays each vector in ``tests/fixtures/mlkem768-xxhfs-vectors.json`` through the
real ``PatternXXhfs`` and asserts the wire bytes match byte for byte. The same
fixture is intended to be consumed by the Rust and JS implementations, so a change
that alters the wire format fails here rather than during manual interop.

libp2p/specs#723 asks for exactly this.

Generated by ``scripts/gen_pq_test_vectors.py``. If a wire-format change is
deliberate, regenerate the fixture in the same commit and say so in the PR — a
silent regeneration defeats the purpose of the file.
"""

import importlib.util
import json
from pathlib import Path

import pytest
import trio

_REPO_ROOT = Path(__file__).resolve().parents[4]
_FIXTURE = _REPO_ROOT / "tests" / "fixtures" / "mlkem768-xxhfs-vectors.json"
_GENERATOR = _REPO_ROOT / "scripts" / "gen_pq_test_vectors.py"

pytestmark = pytest.mark.trio


def _load_generator():
    """
    Import the generator module by path.

    The test replays vectors using the generator's own seeding helpers rather than
    reimplementing them, so there is exactly one definition of "what seed produces
    what handshake". A second copy here could drift from the fixture silently.
    """
    if not _GENERATOR.exists():
        pytest.skip(f"generator missing: {_GENERATOR}")
    spec = importlib.util.spec_from_file_location("_pq_vector_gen", _GENERATOR)
    assert spec is not None and spec.loader is not None, (
        f"could not build an import spec for {_GENERATOR}"
    )
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def _load_fixture() -> dict:
    if not _FIXTURE.exists():
        pytest.skip(f"vector fixture missing: {_FIXTURE}")
    return json.loads(_FIXTURE.read_text(encoding="utf-8"))


class TestFixtureShape:
    """The fixture should describe what it pins, not just contain hex."""

    async def test_protocol_identifiers(self) -> None:
        doc = _load_fixture()
        assert doc["protocol"] == "Noise_XXhfs_25519+MLKEM768_ChaChaPoly_SHA256"
        assert doc["protocol_id"] == "/noise-mlkem768-hfs/0.2.0"

    async def test_has_vectors(self) -> None:
        doc = _load_fixture()
        assert len(doc["vectors"]) >= 1

    async def test_message_sizes_match_the_documented_layout(self) -> None:
        """Message A is fixed-size: e_pk(32) || e1_pk(1184)."""
        doc = _load_fixture()
        for v in doc["vectors"]:
            assert v["msg_a_bytes"] == 32 + 1184, (
                f"vector {v['vector_index']}: message A should be 1216 B "
                f"(32 B X25519 + 1184 B ML-KEM-768 public key), "
                f"got {v['msg_a_bytes']}"
            )
            assert len(bytes.fromhex(v["msg_a"])) == v["msg_a_bytes"]
            assert len(bytes.fromhex(v["msg_b"])) == v["msg_b_bytes"]
            assert len(bytes.fromhex(v["msg_c"])) == v["msg_c_bytes"]

    async def test_kem_public_key_is_mlkem768_sized(self) -> None:
        doc = _load_fixture()
        for v in doc["vectors"]:
            assert len(bytes.fromhex(v["ephemeral_kem_i_public"])) == 1184

    async def test_message_a_embeds_the_advertised_keys(self) -> None:
        """Message A is unencrypted, so its contents are directly checkable."""
        doc = _load_fixture()
        for v in doc["vectors"]:
            msg_a = bytes.fromhex(v["msg_a"])
            assert msg_a[:32] == bytes.fromhex(v["ephemeral_dh_i_public"])
            assert msg_a[32:] == bytes.fromhex(v["ephemeral_kem_i_public"])


class TestVectorReplay:
    """The actual KAT: re-run each handshake and compare the wire bytes."""

    async def test_all_vectors_reproduce(self) -> None:
        doc = _load_fixture()
        gen = _load_generator()

        mismatches: list[str] = []
        for v in doc["vectors"]:
            idx = v["vector_index"]
            base = 0x10 + (idx - 1) * 0x10
            produced = await gen._run_one(idx, base)

            for field in (
                "msg_a",
                "msg_b",
                "msg_c",
                "msg_a_bytes",
                "msg_b_bytes",
                "msg_c_bytes",
                "ephemeral_kem_i_public",
                "ephemeral_dh_i_public",
                "ephemeral_dh_r_public",
                "static_i_public",
                "static_r_public",
            ):
                if produced[field] != v[field]:
                    mismatches.append(
                        f"vector {idx}, field {field!r}: "
                        f"fixture={str(v[field])[:32]}... "
                        f"produced={str(produced[field])[:32]}..."
                    )

        assert not mismatches, (
            "Handshake output no longer matches the pinned vectors:\n  "
            + "\n  ".join(mismatches)
            + "\n\nIf this change is intentional, regenerate with "
            "`python scripts/gen_pq_test_vectors.py` and note the wire-format "
            "change in the PR description."
        )

    async def test_replay_is_deterministic(self) -> None:
        """Two runs of the same vector must agree, or the fixture is meaningless."""
        gen = _load_generator()
        first = await gen._run_one(1, 0x10)
        second = await gen._run_one(1, 0x10)
        assert first == second


class TestVectorsAreDistinct:
    """Different seeds must give different handshakes, or the seeding is broken."""

    async def test_vectors_differ_from_each_other(self) -> None:
        doc = _load_fixture()
        if len(doc["vectors"]) < 2:
            pytest.skip("need at least two vectors")
        seen: set[str] = set()
        for v in doc["vectors"]:
            assert v["msg_a"] not in seen, (
                f"vector {v['vector_index']} has the same message A as an earlier "
                "vector — the seeds are not actually distinct"
            )
            seen.add(v["msg_a"])


async def test_trio_is_the_runner() -> None:
    """Guard: these tests need the trio runner, not asyncio."""
    assert trio.current_time() >= 0
