# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: libp2p/transport/webrtc/signaling_pb/signaling.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'libp2p/transport/webrtc/signaling_pb/signaling.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n4libp2p/transport/webrtc/signaling_pb/signaling.proto\x12\x10webrtc.signaling\"\x9f\x01\n\x10SignalingMessage\x12\x35\n\x04type\x18\x01 \x01(\x0e\x32\'.webrtc.signaling.SignalingMessage.Type\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"F\n\x04Type\x12\r\n\tSDP_OFFER\x10\x00\x12\x0e\n\nSDP_ANSWER\x10\x01\x12\x11\n\rICE_CANDIDATE\x10\x02\x12\x0c\n\x08ICE_DONE\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'libp2p.transport.webrtc.signaling_pb.signaling_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SIGNALINGMESSAGE']._serialized_start=75
  _globals['_SIGNALINGMESSAGE']._serialized_end=234
  _globals['_SIGNALINGMESSAGE_TYPE']._serialized_start=164
  _globals['_SIGNALINGMESSAGE_TYPE']._serialized_end=234
# @@protoc_insertion_point(module_scope)
