SERVICE_PROTOCOL_ID = "/service-discovery/1.0.0"
DHT_NAMESPACE = b"service-discovery:"

RECORD_VERSION = 1
RECORD_MAX_AGE_SECONDS = 300
RECORD_REFRESH_INTERVAL = 120
DHT_GET_TIMEOUT = 10
MAX_RESOLVED_PEERS = 5

DEFAULT_LISTEN_ADDRS = [
    "/ip4/0.0.0.0/tcp/0",
]
