"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import libp2p.crypto.pb.crypto_pb2
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Envelope(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PUBLIC_KEY_FIELD_NUMBER: builtins.int
    PAYLOAD_TYPE_FIELD_NUMBER: builtins.int
    PAYLOAD_FIELD_NUMBER: builtins.int
    SIGNATURE_FIELD_NUMBER: builtins.int
    payload_type: builtins.bytes
    """payload_type encodes the type of payload, so that it can be deserialized
    deterministically.
    """
    payload: builtins.bytes
    """payload is the actual payload carried inside this envelope."""
    signature: builtins.bytes
    """signature is the signature produced by the private key corresponding to
    the enclosed public key, over the payload, prefixing a domain string for
    additional security.
    """
    @property
    def public_key(self) -> libp2p.crypto.pb.crypto_pb2.PublicKey:
        """public_key is the public key of the keypair the enclosed payload was
        signed with.
        """

    def __init__(
        self,
        *,
        public_key: libp2p.crypto.pb.crypto_pb2.PublicKey | None = ...,
        payload_type: builtins.bytes = ...,
        payload: builtins.bytes = ...,
        signature: builtins.bytes = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["public_key", b"public_key"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["payload", b"payload", "payload_type", b"payload_type", "public_key", b"public_key", "signature", b"signature"]) -> None: ...

global___Envelope = Envelope
