"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Record(google.protobuf.message.Message):
    """Record represents a dht record that contains a value
    for a key value pair
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    KEY_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    TIMERECEIVED_FIELD_NUMBER: builtins.int
    key: builtins.bytes
    """The key that references this record"""
    value: builtins.bytes
    """The actual value this record is storing"""
    timeReceived: builtins.str
    """Note: These fields were removed from the Record message
    hash of the authors public key
    optional string author = 3;
    A PKI signature for the key+value+author
    optional bytes signature = 4;

    Time the record was received, set by receiver
    """
    def __init__(
        self,
        *,
        key: builtins.bytes = ...,
        value: builtins.bytes = ...,
        timeReceived: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["key", b"key", "timeReceived", b"timeReceived", "value", b"value"]) -> None: ...

global___Record = Record
