# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: libp2p/host/autonat/pb/autonat.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'libp2p/host/autonat/pb/autonat.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$libp2p/host/autonat/pb/autonat.proto\x12\nautonat.pb\"\xb4\x01\n\x07Message\x12#\n\x04type\x18\x01 \x01(\x0e\x32\x10.autonat.pb.TypeH\x00\x88\x01\x01\x12*\n\x04\x64ial\x18\x02 \x01(\x0b\x32\x17.autonat.pb.DialRequestH\x01\x88\x01\x01\x12\x34\n\rdial_response\x18\x03 \x01(\x0b\x32\x18.autonat.pb.DialResponseH\x02\x88\x01\x01\x42\x07\n\x05_typeB\x07\n\x05_dialB\x10\n\x0e_dial_response\"?\n\x0b\x44ialRequest\x12\'\n\x04peer\x18\x01 \x01(\x0b\x32\x14.autonat.pb.PeerInfoH\x00\x88\x01\x01\x42\x07\n\x05_peer\"\x86\x01\n\x0c\x44ialResponse\x12\'\n\x06status\x18\x01 \x01(\x0e\x32\x12.autonat.pb.StatusH\x00\x88\x01\x01\x12\x17\n\nstatusText\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x11\n\x04\x61\x64\x64r\x18\x03 \x01(\x0cH\x02\x88\x01\x01\x42\t\n\x07_statusB\r\n\x0b_statusTextB\x07\n\x05_addr\"1\n\x08PeerInfo\x12\x0f\n\x02id\x18\x01 \x01(\x0cH\x00\x88\x01\x01\x12\r\n\x05\x61\x64\x64rs\x18\x02 \x03(\x0c\x42\x05\n\x03_id*#\n\x04Type\x12\x08\n\x04\x44IAL\x10\x00\x12\x11\n\rDIAL_RESPONSE\x10\x01*a\n\x06Status\x12\x06\n\x02OK\x10\x00\x12\x10\n\x0c\x45_DIAL_ERROR\x10\x64\x12\x12\n\x0e\x45_DIAL_REFUSED\x10\x65\x12\x12\n\rE_BAD_REQUEST\x10\xc8\x01\x12\x15\n\x10\x45_INTERNAL_ERROR\x10\xac\x02\x32=\n\x07\x41utoNAT\x12\x32\n\x04\x44ial\x12\x13.autonat.pb.Message\x1a\x13.autonat.pb.Message\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'libp2p.host.autonat.pb.autonat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TYPE']._serialized_start=488
  _globals['_TYPE']._serialized_end=523
  _globals['_STATUS']._serialized_start=525
  _globals['_STATUS']._serialized_end=622
  _globals['_MESSAGE']._serialized_start=53
  _globals['_MESSAGE']._serialized_end=233
  _globals['_DIALREQUEST']._serialized_start=235
  _globals['_DIALREQUEST']._serialized_end=298
  _globals['_DIALRESPONSE']._serialized_start=301
  _globals['_DIALRESPONSE']._serialized_end=435
  _globals['_PEERINFO']._serialized_start=437
  _globals['_PEERINFO']._serialized_end=486
  _globals['_AUTONAT']._serialized_start=624
  _globals['_AUTONAT']._serialized_end=685
# @@protoc_insertion_point(module_scope)
