# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import autonat_pb2 as autonat__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in autonat_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AutoNATStub:
    """AutoNAT service definition (libp2p/specs autonat-v1, Recommendation).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Dial = channel.unary_unary(
                '/autonat.pb.AutoNAT/Dial',
                request_serializer=autonat__pb2.Message.SerializeToString,
                response_deserializer=autonat__pb2.Message.FromString,
                _registered_method=True)


class AutoNATServicer:
    """AutoNAT service definition (libp2p/specs autonat-v1, Recommendation).
    """

    def Dial(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AutoNATServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Dial': grpc.unary_unary_rpc_method_handler(
                    servicer.Dial,
                    request_deserializer=autonat__pb2.Message.FromString,
                    response_serializer=autonat__pb2.Message.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'autonat.pb.AutoNAT', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('autonat.pb.AutoNAT', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AutoNAT:
    """AutoNAT service definition (libp2p/specs autonat-v1, Recommendation).
    """

    @staticmethod
    def Dial(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autonat.pb.AutoNAT/Dial',
            autonat__pb2.Message.SerializeToString,
            autonat__pb2.Message.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
