syntax = "proto3";

package autonat.pb;

// AutoNAT service definition
service AutoNAT {
  rpc Dial (Message) returns (Message) {}
}

// Message types
enum Type {
  DIAL = 0;
  DIAL_RESPONSE = 1;
}

// Status codes
enum Status {
  OK = 0;
  E_DIAL_ERROR = 100;
  E_DIAL_REFUSED = 101;
  E_BAD_REQUEST = 200;
  E_INTERNAL_ERROR = 300;
}

// Main message
message Message {
  optional Type type = 1;
  optional DialRequest dial = 2;
  optional DialResponse dial_response = 3;
}

// Dial request
message DialRequest {
  optional PeerInfo peer = 1;
}

// Dial response
message DialResponse {
  optional Status status = 1;
  optional string statusText = 2;
  optional bytes addr = 3;
}

// Peer information
message PeerInfo {
  optional bytes id = 1;
  repeated bytes addrs = 2;
}
