"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Message(_message.Message):
    """Main message"""

    DESCRIPTOR: _descriptor.Descriptor

    class _MessageType:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _MessageTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[Message._MessageType.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        DIAL: Message._MessageType.ValueType  # 0
        DIAL_RESPONSE: Message._MessageType.ValueType  # 1

    class MessageType(_MessageType, metaclass=_MessageTypeEnumTypeWrapper): ...
    DIAL: Message.MessageType.ValueType  # 0
    DIAL_RESPONSE: Message.MessageType.ValueType  # 1

    class _ResponseStatus:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _ResponseStatusEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[Message._ResponseStatus.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        OK: Message._ResponseStatus.ValueType  # 0
        E_DIAL_ERROR: Message._ResponseStatus.ValueType  # 100
        E_DIAL_REFUSED: Message._ResponseStatus.ValueType  # 101
        E_BAD_REQUEST: Message._ResponseStatus.ValueType  # 200
        E_INTERNAL_ERROR: Message._ResponseStatus.ValueType  # 300

    class ResponseStatus(_ResponseStatus, metaclass=_ResponseStatusEnumTypeWrapper): ...
    OK: Message.ResponseStatus.ValueType  # 0
    E_DIAL_ERROR: Message.ResponseStatus.ValueType  # 100
    E_DIAL_REFUSED: Message.ResponseStatus.ValueType  # 101
    E_BAD_REQUEST: Message.ResponseStatus.ValueType  # 200
    E_INTERNAL_ERROR: Message.ResponseStatus.ValueType  # 300

    @_typing.final
    class PeerInfo(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        ID_FIELD_NUMBER: _builtins.int
        ADDRS_FIELD_NUMBER: _builtins.int
        id: _builtins.bytes
        @_builtins.property
        def addrs(self) -> _containers.RepeatedScalarFieldContainer[_builtins.bytes]: ...
        def __init__(
            self,
            *,
            id: _builtins.bytes | None = ...,
            addrs: _abc.Iterable[_builtins.bytes] | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["id", b"id"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["addrs", b"addrs", "id", b"id"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class Dial(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        PEER_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def peer(self) -> Global___Message.PeerInfo: ...
        def __init__(
            self,
            *,
            peer: Global___Message.PeerInfo | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["peer", b"peer"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["peer", b"peer"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class DialResponse(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        STATUS_FIELD_NUMBER: _builtins.int
        STATUSTEXT_FIELD_NUMBER: _builtins.int
        ADDR_FIELD_NUMBER: _builtins.int
        status: Global___Message.ResponseStatus.ValueType
        statusText: _builtins.str
        addr: _builtins.bytes
        def __init__(
            self,
            *,
            status: Global___Message.ResponseStatus.ValueType | None = ...,
            statusText: _builtins.str | None = ...,
            addr: _builtins.bytes | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["addr", b"addr", "status", b"status", "statusText", b"statusText"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["addr", b"addr", "status", b"status", "statusText", b"statusText"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    TYPE_FIELD_NUMBER: _builtins.int
    DIAL_FIELD_NUMBER: _builtins.int
    DIALRESPONSE_FIELD_NUMBER: _builtins.int
    type: Global___Message.MessageType.ValueType
    @_builtins.property
    def dial(self) -> Global___Message.Dial: ...
    @_builtins.property
    def dialResponse(self) -> Global___Message.DialResponse: ...
    def __init__(
        self,
        *,
        type: Global___Message.MessageType.ValueType | None = ...,
        dial: Global___Message.Dial | None = ...,
        dialResponse: Global___Message.DialResponse | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["dial", b"dial", "dialResponse", b"dialResponse", "type", b"type"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["dial", b"dial", "dialResponse", b"dialResponse", "type", b"type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Message: _TypeAlias = Message  # noqa: Y015
