# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: identify.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='identify.proto',
  package='identify.pb',
  syntax='proto2',
  serialized_pb=_b('\n\x0eidentify.proto\x12\x0bidentify.pb\"\x8a\x01\n\x08Identify\x12\x17\n\x0fprotocolVersion\x18\x05 \x01(\t\x12\x14\n\x0c\x61gentVersion\x18\x06 \x01(\t\x12\x11\n\tpublicKey\x18\x01 \x01(\x0c\x12\x13\n\x0blistenAddrs\x18\x02 \x03(\x0c\x12\x14\n\x0cobservedAddr\x18\x04 \x01(\x0c\x12\x11\n\tprotocols\x18\x03 \x03(\t')
)




_IDENTIFY = _descriptor.Descriptor(
  name='Identify',
  full_name='identify.pb.Identify',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='protocolVersion', full_name='identify.pb.Identify.protocolVersion', index=0,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='agentVersion', full_name='identify.pb.Identify.agentVersion', index=1,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='publicKey', full_name='identify.pb.Identify.publicKey', index=2,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='listenAddrs', full_name='identify.pb.Identify.listenAddrs', index=3,
      number=2, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='observedAddr', full_name='identify.pb.Identify.observedAddr', index=4,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='protocols', full_name='identify.pb.Identify.protocols', index=5,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=170,
)

DESCRIPTOR.message_types_by_name['Identify'] = _IDENTIFY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Identify = _reflection.GeneratedProtocolMessageType('Identify', (_message.Message,), dict(
  DESCRIPTOR = _IDENTIFY,
  __module__ = 'identify_pb2'
  # @@protoc_insertion_point(class_scope:identify.pb.Identify)
  ))
_sym_db.RegisterMessage(Identify)


# @@protoc_insertion_point(module_scope)
