# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: autonat.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rautonat.proto\x12\nautonat.pb\"\xeb\x02\n\x07Message\x12-\n\x04type\x18\x01 \x02(\x0e\x32\x1f.autonat.pb.Message.MessageType\x12&\n\x04\x64ial\x18\x02 \x01(\x0b\x32\x18.autonat.pb.Message.Dial\x12\x37\n\rdial_response\x18\x03 \x01(\x0b\x32 .autonat.pb.Message.DialResponse\x1a&\n\x04\x44ial\x12\x0f\n\x07peer_id\x18\x01 \x02(\x0c\x12\r\n\x05\x61\x64\x64rs\x18\x02 \x03(\x0c\x1aP\n\x0c\x44ialResponse\x12\x32\n\x06status\x18\x01 \x02(\x0e\x32\".autonat.pb.Message.ResponseStatus\x12\x0c\n\x04\x61\x64\x64r\x18\x02 \x01(\x0c\"*\n\x0bMessageType\x12\x08\n\x04\x44IAL\x10\x00\x12\x11\n\rDIAL_RESPONSE\x10\x01\"*\n\x0eResponseStatus\x12\x06\n\x02OK\x10\x00\x12\x10\n\x0c\x45_DIAL_ERROR\x10\x64')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'autonat_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGE._serialized_start=30
  _MESSAGE._serialized_end=393
  _MESSAGE_DIAL._serialized_start=185
  _MESSAGE_DIAL._serialized_end=223
  _MESSAGE_DIALRESPONSE._serialized_start=225
  _MESSAGE_DIALRESPONSE._serialized_end=305
  _MESSAGE_MESSAGETYPE._serialized_start=307
  _MESSAGE_MESSAGETYPE._serialized_end=349
  _MESSAGE_RESPONSESTATUS._serialized_start=351
  _MESSAGE_RESPONSESTATUS._serialized_end=393
# @@protoc_insertion_point(module_scope)
