"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class Message(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Flag:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _FlagEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Message._Flag.ValueType], builtins.type):  # noqa: F821
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        FIN: Message._Flag.ValueType  # 0
        """The sender will no longer send messages on the stream. The recipient
        should send a FIN_ACK back to the sender.
        """
        STOP_SENDING: Message._Flag.ValueType  # 1
        """The sender will no longer read messages on the stream. Incoming data is
        being discarded on receipt.
        """
        RESET: Message._Flag.ValueType  # 2
        """The sender abruptly terminates the sending part of the stream. The
        receiver can discard any data that it already received on that stream.
        """
        FIN_ACK: Message._Flag.ValueType  # 3
        """The sender previously received a FIN.
        Workaround for https://bugs.chromium.org/p/chromium/issues/detail?id=1484907
        """

    class Flag(_Flag, metaclass=_FlagEnumTypeWrapper): ...
    FIN: Message.Flag.ValueType  # 0
    """The sender will no longer send messages on the stream. The recipient
    should send a FIN_ACK back to the sender.
    """
    STOP_SENDING: Message.Flag.ValueType  # 1
    """The sender will no longer read messages on the stream. Incoming data is
    being discarded on receipt.
    """
    RESET: Message.Flag.ValueType  # 2
    """The sender abruptly terminates the sending part of the stream. The
    receiver can discard any data that it already received on that stream.
    """
    FIN_ACK: Message.Flag.ValueType  # 3
    """The sender previously received a FIN.
    Workaround for https://bugs.chromium.org/p/chromium/issues/detail?id=1484907
    """

    FLAG_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    flag: global___Message.Flag.ValueType
    message: builtins.bytes
    def __init__(
        self,
        *,
        flag: global___Message.Flag.ValueType | None = ...,
        message: builtins.bytes | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["_flag", b"_flag", "_message", b"_message", "flag", b"flag", "message", b"message"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["_flag", b"_flag", "_message", b"_message", "flag", b"flag", "message", b"message"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_flag", b"_flag"]) -> typing_extensions.Literal["flag"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["_message", b"_message"]) -> typing_extensions.Literal["message"] | None: ...

global___Message = Message
