"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Envelope(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PUBLIC_KEY_FIELD_NUMBER: builtins.int
    PAYLOAD_TYPE_FIELD_NUMBER: builtins.int
    PAYLOAD_FIELD_NUMBER: builtins.int
    SIGNATURE_FIELD_NUMBER: builtins.int
    public_key: builtins.bytes
    payload_type: builtins.bytes
    payload: builtins.bytes
    signature: builtins.bytes
    def __init__(
        self,
        *,
        public_key: builtins.bytes = ...,
        payload_type: builtins.bytes = ...,
        payload: builtins.bytes = ...,
        signature: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["payload", b"payload", "payload_type", b"payload_type", "public_key", b"public_key", "signature", b"signature"]) -> None: ...

global___Envelope = Envelope 