"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class PeerRecord(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PEER_ID_FIELD_NUMBER: builtins.int
    ADDRS_FIELD_NUMBER: builtins.int
    SEQ_FIELD_NUMBER: builtins.int
    peer_id: builtins.bytes
    seq: builtins.int
    @property
    def addrs(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bytes]: ...
    def __init__(
        self,
        *,
        peer_id: builtins.bytes = ...,
        addrs: collections.abc.Iterable[builtins.bytes] | None = ...,
        seq: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["addrs", b"addrs", "peer_id", b"peer_id", "seq", b"seq"]) -> None: ...

global___PeerRecord = PeerRecord 