# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from libp2p.crypto.pb.crypto_pb2 import (
    PublicKey as libp2p___crypto___pb___crypto_pb2___PublicKey,
)

from typing import (
    Optional as typing___Optional,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


class Exchange(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    id = ... # type: bytes

    @property
    def pubkey(self) -> libp2p___crypto___pb___crypto_pb2___PublicKey: ...

    def __init__(self,
        *,
        id : typing___Optional[bytes] = None,
        pubkey : typing___Optional[libp2p___crypto___pb___crypto_pb2___PublicKey] = None,
        ) -> None: ...
    @classmethod
    def FromString(cls, s: bytes) -> Exchange: ...
    def MergeFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    def CopyFrom(self, other_msg: google___protobuf___message___Message) -> None: ...
    if sys.version_info >= (3,):
        def HasField(self, field_name: typing_extensions___Literal[u"id",u"pubkey"]) -> bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"id",u"pubkey"]) -> None: ...
    else:
        def HasField(self, field_name: typing_extensions___Literal[u"id",b"id",u"pubkey",b"pubkey"]) -> bool: ...
        def ClearField(self, field_name: typing_extensions___Literal[u"id",b"id",u"pubkey",b"pubkey"]) -> None: ...
