# Type stubs for the miniupnpc C extension API used by py-libp2p.
# Validated against miniupnpc>=2.3,<3.0 for issue #1009.

class UPnP:
    lanaddr: str | None

    def __init__(self) -> None: ...
    def discover(self) -> int: ...
    def selectigd(self) -> str | None: ...
    def externalipaddress(self) -> str | None: ...
    def connectiontype(self) -> str | None: ...
    def addportmapping(
        self,
        external_port: int,
        protocol: str,
        internal_client: str | None,
        internal_port: int,
        description: str,
        remote_host: str,
    ) -> bool: ...
    def deleteportmapping(self, external_port: int, protocol: str) -> bool: ...
