"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class NoiseHandshakePayload(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IDENTITY_KEY_FIELD_NUMBER: builtins.int
    IDENTITY_SIG_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    identity_key: builtins.bytes
    identity_sig: builtins.bytes
    data: builtins.bytes
    def __init__(
        self,
        *,
        identity_key: builtins.bytes = ...,
        identity_sig: builtins.bytes = ...,
        data: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["data", b"data", "identity_key", b"identity_key", "identity_sig", b"identity_sig"]) -> None: ...

global___NoiseHandshakePayload = NoiseHandshakePayload
