# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: signaling_message.proto
# Protobuf Python Version: 6.33.1
# mypy: ignore-errors
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'signaling_message.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17signaling_message.proto\x12\x19webrtc.private_to_private\"\xa4\x01\n\x07Message\x12:\n\x04type\x18\x01 \x01(\x0e\x32\'.webrtc.private_to_private.Message.TypeH\x00\x88\x01\x01\x12\x11\n\x04\x64\x61ta\x18\x02 \x01(\tH\x01\x88\x01\x01\"8\n\x04Type\x12\r\n\tSDP_OFFER\x10\x00\x12\x0e\n\nSDP_ANSWER\x10\x01\x12\x11\n\rICE_CANDIDATE\x10\x02\x42\x07\n\x05_typeB\x07\n\x05_datab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'signaling_message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGE']._serialized_start=55
  _globals['_MESSAGE']._serialized_end=219
  _globals['_MESSAGE_TYPE']._serialized_start=145
  _globals['_MESSAGE_TYPE']._serialized_end=201
# @@protoc_insertion_point(module_scope)
