name: Publish to PyPI

on:
  push:
    tags:
      - 'v*' # Triggers on any tag push starting with 'v', e.g., 'v0.1.0'

jobs:
  pypi-publish:
    name: Build and publish Python distribution 📦 to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/py-ipfs-lite
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
      contents: read
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          
      - name: Install build dependencies
        run: pip install build
        
      - name: Build a binary wheel and a source tarball
        run: python -m build
        
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
